# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='昵称', max_length=64, unique=True)),
                ('password', models.CharField(help_text='密码', max_length=128)),
                ('icon', models.ImageField(help_text='头像', upload_to='')),
                ('age', models.IntegerField(help_text='年龄')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '保密')], help_text='性别', max_length=8)),
            ],
        ),
    ]
