# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(help_text='头像', upload_to='medias'),
        ),
    ]
