# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180827_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(help_text='头像', upload_to=''),
        ),
    ]
